[[plugins]]
repo = 'Shougo/ddc.vim'
on_event='InsertEnter'
hook_source = '''
call ddc#custom#patch_global('sources', ['around', 'buffer', 'eskk'])

call ddc#custom#patch_filetype(
  \ ['typescript', 'typescriptreact', 'typescript.tsx'],
  \ 'sources', ['nvimlsp'])

call ddc#custom#patch_global('sourceOptions', {
  \ '_' : {
  \   'matchers' : ['matcher_head'],
  \   'sorters' : ['sorter_rank'],
  \ }})

call ddc#custom#patch_global('sourceOptions', {
  \ 'around' : {'mark' : 'A'},
  \ 'buffer' : {'mark' : 'B', 'requireSameFiletype' : 'v:false'},
  \ 'eskk' : {'mark' : 'eskk', 'matchers': [], 'sorters': []},
  \ 'nvimlsp' : {'mark' : 'lsp', 'forceCompletionPattern': '\.|:|->'},
  \ })

inoremap <silent><expr> <TAB>
  \ pumvisible() ? "\<C-n>" : "\<TAB>"

call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'tyru/eskk.vim'
on_source = 'ddc.vim'
hook_source= '''
let g:eskk#large_dictionary = {
\	'path': "~/.skk/SKK-JISYO.L",
\	'sorted': 1,
\	'encoding': 'euc-jp',
\}

let g:eskk#tab_select_completion = 1
let g:eskk#marker_henkan = "@"
let g:eskk#marker_henkan_select = "#"
'''

[[plugins]]
repo = 'willelz/teastylua.nvim'
on_ft = "lua"
hook_source = '''
nmap <Space>f <Plug>teastyluaFormat
'''
