[[plugins]]
repo = 'Shougo/ddc.vim'
on_event='InsertEnter'
hook_source = '''
call ddc#custom#patch_global('sources', ['around', 'buffer', 'skkeleton'])

call ddc#custom#patch_global('sourceOptions', {
  \ '_' : {
  \   'matchers' : ['matcher_head'],
  \   'sorters' : ['sorter_rank'],
  \ }})

call ddc#custom#patch_global('sourceOptions', {
  \ 'around' : {'mark' : 'A'},
  \ 'buffer' : {'mark' : 'B', 'requireSameFiletype' : 'v:false'},
  \ 'skkeleton' : {'mark' : 'skk'},
  \ 'nvimlsp' : {'mark' : 'lsp', 'forceCompletionPattern': '\.|:|->'},
  \ })

call ddc#custom#patch_filetype(
  \ ['typescript', 'typescriptreact', 'typescript.tsx'],
  \ 'sources', ['nvim-lsp', 'around', 'buffer', 'skkeleton'])

inoremap <silent><expr> <TAB>
  \ pumvisible() ? "\<C-n>" : "\<TAB>"

call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo='vim-skk/skkeleton '
on_event = 'InsertEnter'
hook_source='''
function! s:skkeleton_init() abort
  call skkeleton#config({
    \ 'globalJisyo' : $HOME .. '/.skk/SKK-JISYO.L',
    \ 'markerHenkan' : '',
    \ 'markerHenkanSelect' : '',
    \ })
endfunction

imap <C-j> <Plug>(skkeleton-enable)
cmap <C-j> <Plug>(skkeleton-enable)

autocmd User skkeleton-initialize-pre call s:skkeleton_init()
'''

[[plugins]]
repo = 'willelz/teastylua.nvim'
on_ft = "lua"
hook_source = '''
nmap <Space>f <Plug>teastyluaFormat
'''
