[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'mhartington/oceanic-next'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'tyru/eskk.vim'
hook_add= '''
let g:eskk#large_dictionary = {
\	'path': "~/.skk/SKK-JISYO.L",
\	'sorted': 1,
\	'encoding': 'euc-jp',
\}

let g:eskk#marker_henkan = ''
let g:eskk#marker_henkan_select = ''
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
nmap s <Nop>
xmap s <Nop>

let g:sandwich_no_initex_ftplugin = 1
let g:sandwich_no_julia_ftplugin = 1
let g:sandwich_no_plaintex_ftplugin = 1
let g:sandwich_no_tex_ftplugin = 1
'''

[[plugins]]
repo = 'voldikss/vim-translator'
hook_add = '''
let g:translator_target_lang = 'ja'
nmap <silent> <Leader>w <Plug>TranslateW
vmap <silent> <Leader>w <Plug>TranslateWV
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
hook_add = '''
let g:haskell_indent_disable = 1
'''

[[plugins]]
repo = 'itchyny/vim-haskell-indent'

[[plugins]]
repo = 'andys8/vim-elm-syntax'

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'
hook_add = '''
let g:comfortable_motion_friction = 50.0
let g:comfortable_motion_air_drag = 5.0
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_lint_on_text_changed="normal"
let g:ale_lint_on_insert_leave=1
let g:ale_linters = {'elm': 'all'}
let g:ale_fixers = {
  \  'typescript' : ['prettier'],
  \  'javascript' : ['prettier'],
  \  'json' : ['prettier'],
  \  'less' : ['prettier'],
  \  'elm' : ['elm-format'],
  \}
let g:ale_fix_on_save=1
'''


[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
set noshowmode

let g:lightline = {
  \  'colorscheme' : 'solarized',
  \  'active' : {
  \    'right' : [ ['lineinfo'],
  \                ['percent'],
  \                ['filetype']]
  \  }
  \}
'''
