[[plugins]]
repo = 'tyru/eskk.vim'
on_event = 'InsertEnter'
hook_source= '''
let g:eskk#large_dictionary = {
\	'path': "~/.skk/SKK-JISYO.L",
\	'sorted': 1,
\	'encoding': 'euc-jp',
\}

let g:eskk#tab_select_completion = 1
let g:eskk#marker_henkan = "@"
let g:eskk#marker_henkan_select = "#"
'''

