[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event='InsertEnter'
hook_source = '''
"<TAB>: completion.
inoremap <silent><expr> <TAB>
	\ pumvisible() ? "\<C-n>" :
	\ <SID>check_back_space() ? "\<TAB>" :
	\ deoplete#manual_complete()
function! s:check_back_space() abort
	let col = col('.') - 1
	return !col || getline('.')[col - 1]  =~ '\s'
endfunction

" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function() abort
  return pumvisible() ? deoplete#close_popup() : "\<CR>"
endfunction

" Use smartcase.
" 大文字が含まれていたら大文字小文字を区別する
call deoplete#custom#option('smart_case', v:true)
"<BS>: close popup and delete backword char.
inoremap <expr><BS> deoplete#smart_close_popup()."\<C-h>"

call deoplete#custom#source('LanguageClient',
  \ 'min_pattern_length',
  \ 2)

call deoplete#enable()
'''

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
on_event='InsertEnter'
build = 'bash ./install.sh'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
on_ft = 'haskell'
rev = 'next'
build = 'bash install.sh'
hook_add='''
let g:LanguageClient_serverCommands = { 'haskell': ['hie-wrapper'] }

noremap <Space> <nop>

nnoremap <Space>ll :call LanguageClient_contextMenu()<CR>
map <Space>lk :call LanguageClient#textDocument_hover()<CR>
map <Space>lg :call LanguageClient#textDocument_definition()<CR>
map <Space>lr :call LanguageClient#textDocument_rename()<CR>
map <Space>lf :call LanguageClient#textDocument_formatting()<CR>
map <Space>lb :call LanguageClient#textDocument_references()<CR>
map <Space>la :call LanguageClient#textDocument_codeAction()<CR>
map <Space>ls :call LanguageClient#textDocument_documentSymbol()<CR>
'''

[[plugins]]
repo = 'mhartington/nvim-typescript'
build = './install.sh'
on_ft = ['typescript', 'typescriptreact']
hook_add = '''
let g:nvim_typescript#type_info_on_hold = 1
let g:nvim_typescript#signature_complete = 0
'''

[[plugins]]
repo = 'kana/vim-smartinput'
on_event='InsertEnter'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['typescript', 'typescriptreact', 'javascript', 'html']
